### PR TITLE
chore: switch to yarn 2

### PR DESCRIPTION
**Pull request by darkbasic**
Notes (blhoward2):
```
If zjs2mqtt is switching over to yarn v2, could you please take a look at the Dockerfile.contrib and make any changes necessary there?
We use that to build custom dockers off any branch on either project
```

### CODE REVIEW

**Comment by AlCalzone** [comment]
You need the .yarn folder. The yarn documentation mentions what should be in gitignore and what not.

**Comment by darkbasic** [comment]
Turns out Dockerfile.contrib was already broken: I've fixed it and made it compatible with berry. By the way, will they ever make the equivalent of v1 --production flag for non-workspaces projects?

**Comment by darkbasic** [comment]
Yes I tested it with darkbasic:feat/yarn2.

**Comment by blhoward2** [comment]
Maybe this is better all around. Note the entry about a target: https://stackoverflow.com/questions/43654656/dockerfile-if-else-condition-with-external-arguments

We'd need to update the docs too and it's a breaking change, which I'm not sure is that big of a deal here.

**Comment by darkbasic** [comment]
@blhoward2 turns out there was already a comment warning about buildkit but somehow I completely skipped it.
The Dockerfile pointed at the Readme which didn't contain any instructions, so I've linked the website instead.

**Pull request merged**
