### PR TITLE
feat: create esbuild bundle for embedded devices

### PR DESCRIPTION
**Pull request by robertsLando**
Ref #3473

### CODE REVIEW

**Comment by dwmw2** [comment]
OK, I have a package building and working with these changes. Thanks! 

https://github.com/nxhack/openwrt-node-packages/commit/bcd6acf5b6cdc26bb301d3530cf110430d5e0f1a

Just a few nits...

To build against the release tarball, I needed to the patches to be against `server/api/{utils.js,ZWaveClient.js}` instead of the corresponding `.ts` files. But that'll just fall out when there's a release.

I also needed to change the `entryPoints` in `esbuild.js`  from `api/bin/www.ts` to `server/bin/www.js` though.

And when the package build does its `npm install`, I end up with the config in `node_modules/zwave-js/node_modules/@zwave-js/config` rather than `node_modules/@zwave-js/config` so for now I just made a symlink and then `npm run bundle` works.

**Comment by robertsLando** [comment]
Humm insteresting... but what tarball are you donwloading? npm tarball?

**Comment by robertsLando** [comment]
Would it help adding a flag like `--use-js-entrypoint` to handle that case on esbuild?

**Comment by dwmw2** [comment]
Or could we make it use server/bin/www.js unconditionally? Don't we always have to build `api/bin/www.ts` → `server/bin/www.js` anyway? The original TypeScript file isn't even in the bundle, surely?

**Comment by dwmw2** [comment]
https://janessagarrow.com/blog/typescript-and-esbuild/ seems to suggest that esbuild allows the `.ts` file to be specified because it might actually get built to multiple *different* `.js` files, for different environments. But that isn't a concern here as we're only building for node, right? So we can just unconditionally list `server/bin/www.js` as the entrypoint without needing an option?

**Comment by robertsLando** [comment]
@dwmw2 reason is that compiling against ts with source maps set to true allows me to have a better stack errors as they will point to ts lines, otherwise it might be difficult to debug things

**Comment by dwmw2** [comment]
Don't you get that from the source maps anyway?

**Comment by robertsLando** [comment]
> Don't you get that from the source maps anyway?

Wrong, If I ship sourcemaps (with also the code inside `api` folder) I get full logs

**Pull request merged**
