### PR TITLE
feat: listen for `node info received` event

### PR DESCRIPTION
**Pull request by robertsLando**
Ref #3936

### CODE REVIEW

**Comment by robertsLando** [comment]
cc @AlCalzone Should I react to this someway?

**Comment by AlCalzone** [comment]
No. It can be used as a hook for automations, no point in doing that in the UI.

**Comment by robertsLando** [comment]
Ok, so I will just emit the event in case someone wants to react to it when using MQTT

**Comment by nmpu** [comment]
> Ok, so I will just emit the event in case someone wants to react to it when using MQTT

I was one of the people who suggested this feature. I've never had a need to use MQTT. What's the simplest way to create a HA trigger?

**Comment by robertsLando** [comment]
@kpine may know, I'm not very expert on HA

**Comment by kpine** [comment]
`zwave_js.event` trigger should work I think. https://www.home-assistant.io/integrations/zwave_js/#zwave_jsevent

But the docs mention "strict validation in place based on all known event types" which makes it less useful. So you may need to submit an HA issue if it doesn't work.

**Comment by nmpu** [comment]
> `zwave_js.event` trigger should work I think. https://www.home-assistant.io/integrations/zwave_js/#zwave_jsevent
> 
> But the docs mention "strict validation in place based on all known event types" which makes it less useful. So you may need to submit an HA issue if it doesn't work.

I have a NuTone NWD500Z dimmer. These are not Plus devices and do not send asynchronous updates to the hub. I have to use polling. There's an undocumented feature where double-tap sends NIF which results in the controller requesting an update. I had requested that NIF generate a distinct event so that I can distinguish it from my polling.

I don't see any new/different activity when I view the EVENTS tab (target device) in Z-Wave JS UI. In my experience, events are unfiltered even if HA doesn't currently support as a trigger, So, I was wondering if this new feature is some pseudo-event which requires another interface to capture. How was this change tested? Can someone post a log showing the expected output? My original issue bounced around for a bit. Maybe what came out the other end is not what I expected?

2025-11-24 16:41:20.342 DRIVER   all queues idle
2025-11-24 16:41:23.605 SERIAL « 0x011200498400380b041104262b2c2773708672f3                          (20 bytes)
2025-11-24 16:41:23.607 SERIAL » [ACK]                                                                   (0x06)
2025-11-24 16:41:23.608 DRIVER « [Node 056] [REQ] [ApplicationUpdateRequest]
2025-11-24 16:41:23.608 CNTRLR « [Node 056] Received updated node info
2025-11-24 16:41:23.609 CNTRLR   [Node 056] Node does not send unsolicited updates; refreshing actuator and sen
                                 sor values...
2025-11-24 16:41:23.610 INFO Z-WAVE: [Node 056] Node info (NIF) received
2025-11-24 16:41:23.613 CNTRLR » [Node 056] requesting current switch state...
2025-11-24 16:41:23.615 DRIVER   one or more queues busy
2025-11-24 16:41:23.616 DRIVER » [Node 056] [REQ] [SendDataBridge]
                                 │ source node id:   1
                                 │ transmit options: 0x25
                                 │ callback id:      207
                                 └─[MultilevelSwitchCCGet]
2025-11-24 16:41:23.616 SERIAL » 0x011000a9000100380226022500000000cfb3                              (18 bytes)
2025-11-24 16:41:23.629 SERIAL « [ACK]                                                                   (0x06)
2025-11-24 16:41:23.630 SERIAL « 0x010401a90152                                                       (6 bytes)
2025-11-24 16:41:23.633 SERIAL » [ACK]                                                                   (0x06)
2025-11-24 16:41:23.637 DRIVER « [RES] [SendDataBridge]
                                   was sent: true
2025-11-24 16:41:23.644 SERIAL « 0x011d00a9cf00000100a97f7f7f7f01010300000000020100007f7f7f7f7f53    (31 bytes)
2025-11-24 16:41:23.645 SERIAL » [ACK]                                                                   (0x06)
2025-11-24 16:41:23.646 DRIVER « [REQ] [SendDataBridge]
                                   callback id:            207
                                   transmit status:        OK, took 10 ms
                                   routing attempts:       1
                                   protocol & route speed: Z-Wave, 40 kbit/s
                                   routing scheme:         LWR
                                   ACK RSSI:               -87 dBm
                                   ACK channel no.:        1
                                   TX channel no.:         1
2025-11-24 16:41:23.655 SERIAL « 0x011100a800000100380326030000a8007f7ff1                            (19 bytes)
2025-11-24 16:41:23.656 SERIAL » [ACK]                                                                   (0x06)
2025-11-24 16:41:23.657 CNTRLR   [Node 056] [~] [Multilevel Switch] currentValue: 0 => 0           [Endpoint 0]
2025-11-24 16:41:23.658 INFO Z-WAVE: [Node 056] Value updated: 38-0-currentValue 0 => 0
2025-11-24 16:41:23.659 DRIVER « [Node 056] [REQ] [BridgeApplicationCommand]
                                 │ RSSI: -88 dBm
                                 └─[MultilevelSwitchCCReport]
                                     current value: 0
``

**Comment by kpine** [comment]
Can't say anything about the events tab, but you see it right here.

> 2025-11-24 16:41:23.610 INFO Z-WAVE: [Node 056] Node info (NIF) received

**Comment by kpine** [comment]
But I think you're limited by HA at this point, if I understand correctly.

The Python library does not support the `node info received` node event: https://github.com/home-assistant-libs/zwave-js-server-python/blob/f2cc662af41459b153cc17631a7efb868387990a/zwave_js_server/model/node/event_model.py#L335-L357

Then the library's event handler skips unsupported events. You might see a debug log message if you turn on debug logging. https://github.com/home-assistant-libs/zwave-js-server-python/blob/f2cc662af41459b153cc17631a7efb868387990a/zwave_js_server/event.py#L76-L82

**Comment by nmpu** [comment]
> Can't say anything about the events tab, but you see it right here.
> 
> > 2025-11-24 16:41:23.610 INFO Z-WAVE: [Node 056] Node info (NIF) received

Yes, that verbose log is from the Z-Wave JS UI * Debug section which shows what's happening on the back end. I'm looking for something new on the client side. It does appear to be a pseudo-event, so probably requires a change in HA triggers or use of MQTT.
```
this.emit(
	'event',
	EventSource.NODE,
	'node info received',
	this.zwaveNodeToJSON(zwaveNode),
)
```

**Comment by kpine** [comment]
To clarify, `INFO Z-WAVE` logs are from Z-Wave JS UI, on the application side (not driver). So I was showing where Z-Wave JS UI is logging the event as it sees it. The code you posted is Z-Wave JS UI's internal handler that will emit an MQTT event in response to that. The other code of that commit is the ZUI event handler (handles the driver events):

https://github.com/zwave-js/zwave-js-ui/blob/a5f401895db29c57cc9e0d35642b299b1c11b80f/api/lib/ZwaveClient.ts#L6268-L6303

Which translates basically to the HA library code I previously posted. HA needs to implement an event handler in its Python library so it won't drop the event. The trigger I posted previously would then support it automatically. The integration uses the same data structure from the library directly in https://github.com/home-assistant/core/blob/6c4296a0de0f79d4e6b0f2591f321f724e49d421/homeassistant/components/zwave_js/triggers/event.py.

**Comment by nmpu** [comment]
> HA needs to implement an event handler in its Python library so it won't drop the event.

I always appreciate your insight. At least we got this far. I realize this is a pretty obscure feature. I'll keep pushing downstream. I guess it all depends on the assigned developer's other priorities.

**Comment by AlCalzone** [comment]
My buddy Claude has some free capacity

**Comment by nmpu** [comment]
> My buddy Claude has some free capacity

Is that the AI thing or a real person? Home Assistant [integration enhancement](https://github.com/orgs/home-assistant/discussions/1950).

**Pull request merged**
