### PR TITLE
fix: rollup not working on arm

### LINKED ISSUE #4007: Version 9.27, unable to build from source
### Checklist

- [X]  I am not using Home Assistant. Or: a developer has told me to come here.
- [X] I have checked the troubleshooting section and my problem is not described there.
- [X] I have read the changelog and my problem is not mentioned there.

### Deploy method

Manually built (git clone - npm run build - npm install

### Z-Wave JS UI version

9.27.2

### ZwaveJS version

n/a

### Describe the bug

Version 9.27, when building from source "npm run build" fails. 
https://zwave-js.github.io/zwave-js-ui/#/getting-started/other-methods?id=nodejs-or-pkg-version

### To Reproduce

git clone https://github.com/zwave-js/zwave-js-ui
cd zwave-js-ui
npm install
npm run build

### Expected behavior

"npm run build" should complete successfully. 

### Additional context

System: Raspberry Pi 3 or 5, RaspberryOS version 12 (bookworm), node version 20.18.0, npm version 10.8.2

Output from "npm run build"

```
> zwave-js-ui@9.27.2 build
> npm-run-all build:*


> zwave-js-ui@9.27.2 build:server
> tsc


> zwave-js-ui@9.27.2 build:ui
> vite build

/home/pi/git/zwave-js-ui/node_modules/rollup/dist/native.js:63
                throw new Error(
                      ^

Error: Cannot find module @rollup/rollup-linux-arm-gnueabihf. npm has a bug related to optional dependencies (https://github.com/npm/cli/issues/4828). Please try `npm i` again after removing both package-lock.json and node_modules directory.
    at requireWithFriendlyError (/home/pi/git/zwave-js-ui/node_modules/rollup/dist/native.js:63:9)
    at Object.<anonymous> (/home/pi/git/zwave-js-ui/node_modules/rollup/dist/native.js:72:76)
    ... 3 lines matching cause stack trace ...
    at Module._load (node:internal/modules/cjs/loader:1104:12)
    at cjsLoader (node:internal/modules/esm/translators:346:17)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/translators:286:7)
    at ModuleJob.run (node:internal/modules/esm/module_job:234:25)
    at async ModuleLoader.import (node:internal/modules/esm/loader:473:24) {
  [cause]: Error: Cannot find module '@rollup/rollup-linux-arm-gnueabihf'
  Require stack:
  - /home/pi/git/zwave-js-ui/node_modules/rollup/dist/native.js
      at Module._resolveFilename (node:internal/modules/cjs/loader:1225:15)
      at Module._load (node:internal/modules/cjs/loader:1051:27)
      at Module.require (node:internal/modules/cjs/loader:1311:19)
      at require (node:internal/modules/helpers:179:18)
      at requireWithFriendlyError (/home/pi/git/zwave-js-ui/node_modules/rollup/dist/native.js:45:10)
      at Object.<anonymous> (/home/pi/git/zwave-js-ui/node_modules/rollup/dist/native.js:72:76)
      at Module._compile (node:internal/modules/cjs/loader:1469:14)
      at Module._extensions..js (node:internal/modules/cjs/loader:1548:10)
      at Module.load (node:internal/modules/cjs/loader:1288:32)
      at Module._load (node:internal/modules/cjs/loader:1104:12) {
    code: 'MODULE_NOT_FOUND',
    requireStack: [ '/home/pi/git/zwave-js-ui/node_modules/rollup/dist/native.js' ]
  }
}

Node.js v20.18.0
ERROR: "build:ui" exited with 1.

```

### PR DESCRIPTION
**Pull request by robertsLando**
Fixes #4007. Ref: https://github.com/rollup/rollup/issues/5194#issuecomment-1833271025

### CODE REVIEW

**Review by AlCalzone — CHANGES_REQUESTED** [review]
I think you need to at least run an `npm install` to have the lockfile updated.

**Comment by robertsLando** [comment]
@AlCalzone I dropped package-lock and run npm i and nothing changed on lock file 🤷🏼‍♂️

**Comment by AlCalzone** [comment]
This isn't working

**Comment by AlCalzone** [comment]
New approach: I uninstalled every dependency that indirectly depended on `rollup`
Added
```
  "overrides": {
    "rollup": "npm:@rollup/wasm-node"
  },
```

Then restored the removed entries in package.json and did `npm install`. Voila:
grafik

**Pull request merged**
