### PR TITLE
chore(deps): enable renovate for dependency management

### PR DESCRIPTION
**Pull request by chrisns**
see https://github.com/chrisns/zwave-js-ui/pulls for its suggested updates
note it handles updating the docker images etc
can configure it to do loads (obvs)

not all the suggestions its making can be merged, but I'm happy to work through making current versions of our deps work as best i can

### CODE REVIEW

**Comment by robertsLando** [comment]
It's ok for me, I would like to know if @AlCalzone agree as we temporary disabled dependabot but renovate should work well

**Comment by AlCalzone** [comment]
Renovate Bot supports yarn, so this seems Ok.
Although dependabot support seems to be just around the corner now. And personally, I prefer the dependabot workflow, even though renovate is more configurable.

**Comment by chrisns** [comment]
agree dependabot is nice since it is github, but sadly not as feature rich :(
renovate I'd say would still have a limited place for maintaining base docker images
so if/when dependabot supports yarn we might find ourselves wanting both but for different sets of deps perhaps?

**Comment by chrisns** [comment]
What if I scope it down to just docker/* which dependabot doesn't do so well

**Comment by robertsLando** [comment]
Ok for me

**Comment by robertsLando** [comment]
@AlCalzone should we enable dependabot again now?

**Comment by AlCalzone** [comment]
Dependabot seems to work with Yarn v3 now. I've gotten some security fixes already and other repos using yarn are completely managed by Dependabot again.

**Comment by chrisns** [comment]
@robertsLando have limited this to just docker+nvm now, so dependabot can carry on doing the npm/yarn stuff

**Review by robertsLando — APPROVED** [review]

**Comment by robertsLando** [comment]
Thanks @chrisns ! 🙏🏼

**Pull request merged**
