### PR TITLE
fix(docker): serialport prebuilds should be ok now, so can skip rebuilding it

### PR DESCRIPTION
**Pull request by chrisns**

### CODE REVIEW

**Review by robertsLando — CHANGES_REQUESTED** [review]
Without that line and the changes I did related to node_modules, the install will be skipped and so the arm builds will ship with the amd64 binaries of serialport (that will not work at all on arms)

**Comment by chrisns** [comment]
hold fire, need to get another PR fixed for serial-port

**Comment by chrisns** [comment]
blocked by https://github.com/serialport/bindings-cpp/pull/163 or move to non-musl (alpine) based image

**Comment by robertsLando** [comment]
#3443 fixes all the problems 🎉

**Pull request closed without merging**
