### PR TITLE
feat(ui): add notice on OTA updates not being complete

### PR DESCRIPTION
**Pull request by LordMike**
I found that I checked the "OTA Updates" but that I actually didn't know what the "No updates available" meant - because I _know_ that there are updates for this device. So I checked, and found old threads etc, but to help future me (and others), I'm making this update :)

image

### CODE REVIEW

**Comment by LordMike** [comment]
I think the message can be further improved by suggesting that users ask their device manufacturers to commit to the firmware repository project :)

**Review by robertsLando — CHANGES_REQUESTED** [review]
> I think the message can be further improved by suggesting that users ask their device manufacturers to commit to the firmware repository project :)

I agree, go for it :)

**Comment by LordMike** [comment]
I've made an initial attempt - I'm editing this in Github, so someone else will have to do the linting later on :P

image

**Comment by robertsLando** [comment]
There was a bot for this but seems stopped working, maybe the project rename broke it @AlCalzone ?

**Comment by AlCalzone** [comment]
A bot for what?

**Comment by LordMike** [comment]
> A bot for what?

I think there might have been a github bot/action that provided a "fix formatting for me" button to make a commit that fixes formatting/lint errors.

**Comment by AlCalzone** [comment]
Oh, @robertsLando you might need to reinstall the app in your repo. Not sure though if that's the issue.

**Comment by robertsLando** [comment]
> Oh, @robertsLando you might need to reinstall the app in your repo

It's already installed, I dunno what's wrong, maybe some error on bot side?

**Comment by robertsLando** [comment]
@zwave-js-bot fix lint

**Comment by robertsLando** [comment]
Ok so seems bot is working but it's not commenting

**Review by robertsLando — APPROVED** [review]

**Pull request merged**
