### PR TITLE
fix(ui): use inverted checkbox to clarify settings

### PR DESCRIPTION
**Pull request by robertsLando**

### CODE REVIEW

**Comment by robertsLando** [comment]
cc @AlCalzone

**Comment by AlCalzone** [comment]
There are a few more:
grafik
(also why is this a checkbox when all others are a toggle?)

grafik

grafik

**Comment by robertsLando** [comment]
So should I only change the dns discovery one?

**Comment by AlCalzone** [comment]
I guess, yeah

**Pull request merged**
