### PR TITLE
fix: enable "real" client IP visibility even behind proxies

### PR DESCRIPTION
**Pull request by 999LV**
Complements https://github.com/zwave-js/zwave-js-ui/commit/b1dc1a4f535fbba65020d8e45943bb1c8e7e4e33

### CODE REVIEW

**Comment by robertsLando** [comment]
I think it would be better to enable this based on an env var. @chrisns agree?

**Comment by chrisns** [comment]
I don't think we actually care in zwjs-ui what the ip is, apart from maybe logging?

agree, if we're going to define it must be an env var / config

setting trust to `true` is a really bad idea (though at the user's discretion if its configurable), it should really be more specific, and must **only** enabled in situations where a proxy is present, otherwise an actor with direct access could use it to masquerade as any ip they like.

I suspect most users don't have this behind a proxy (which is why auth exists within the app etc)

https://expressjs.com/en/guide/behind-proxies.html

**Comment by chrisns** [comment]
moved to draft, if its changed to be configurable, somewhere then it can be ready to review again.

**Comment by 999LV** [comment]
Got your points, thank you. I'll resubmit based on an environment variable configuration (with default to 'false' so that it is really a user conscious decision)

**Comment by 999LV** [comment]
On thinking further about this « origin ip » topic, I think it is better to withdraw that pull request indeed since it does not bring much but creates other risks. Apologies.

**Pull request closed without merging**
