### PR TITLE
fix: set default host to `::`

### LINKED ISSUE #3347: Also listen to IPv6 by default
**Is your feature request related to a problem? Please describe.**
zwave-js-ui listens to 0.0.0.0:8091 by default, which is IPv4 only, so it doesn't respond to IPv6 requests.

**Describe the solution you'd like**
It would be nice to listen to IPv6 as well by default since IPv6 is widely used everywhere nowadays. All that's needed is bind to `::` instead of `0.0.0.0` (e.g. by setting `HOST="::"` in the current version). Imho, this should be the default. (Generally, it works well binding to `::` as this listens on IPv6 and IPv4 on dual stack systems. Not sure if there are systems out there that would bind to IPv6 only with `::`)

**Describe alternatives you've considered**
The alternative to listen to IPv6 only by default would be possible but maybe a step too far for now ;)

### PR DESCRIPTION
**Pull request by robertsLando**
Fixes #3347

### CODE REVIEW

**Comment by Skullduggeryism** [comment]
just an FYI - this change broke my docker-compose environment where I have ipv6 disabled.  I had to fix by setting an environment variable of HOST and setting it to the value of the container IP

**Comment by bpawulski** [comment]
@Skullduggeryism I'm probably having similar problem to yours. 
After updating the container to 9.2 it's not starting with the error: 
`2023-10-18 16:19:03.238 WARN STORE: scenes.json not found
Error: listen EAFNOSUPPORT: address family not supported :::8091
    at Server.setupListenHandle [as _listen2] (node:net:1723:21)
    at listenInCluster (node:net:1788:12)
    at doListen (node:net:1937:7)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)` 
Could you please give a little bit more details was it the same as you have seen and how you fixed it. Thank you!

**Comment by robertsLando** [comment]
Can someone of you give a try to: https://github.com/zwave-js/zwave-js-ui/pull/3362 ?

I can build a test docker container for it

**Comment by bpawulski** [comment]
@robertsLando Sure, I can. Send me please the new container.

**Comment by robertsLando** [comment]
I have triggered this workflow: https://github.com/zwave-js/zwave-js-ui/actions/runs/6571215103

Once it ends, you can use docker `test` tag

**Comment by bpawulski** [comment]
@robertsLando : just pulled the test tag `Digest: sha256:2014a9da749da02d3548e3cb091ae9f185af565fed18e899e3dadfcbfc1da8da`

And it works fine (after 3 min of interacting with it). Thank you!

**Comment by robertsLando** [comment]
@bpawulski Do you have ipv6 disabled?

**Comment by bpawulski** [comment]
@robertsLando: Yes i do  
bartek@ubuntuser:~$ cat /sys/module/ipv6/parameters/disable
1

**Comment by robertsLando** [comment]
Thanks for your report!

**Comment by Skullduggeryism** [comment]
> @Skullduggeryism I'm probably having similar problem to yours. After updating the container to 9.2 it's not starting with the error:
> 
> `2023-10-18 16:19:03.238 WARN STORE: scenes.json not found Error: listen EAFNOSUPPORT: address family not supported :::8091 at Server.setupListenHandle [as _listen2] (node:net:1723:21) at listenInCluster (node:net:1788:12) at doListen (node:net:1937:7) at processTicksAndRejections (node:internal/process/task_queues:83:21)`
> 
> Could you please give a little bit more details was it the same as you have seen and how you fixed it. Thank you!

That is correct, I got the error "EAFNOSUPPORT: address family not supported :::8091"

To fix (in docker-compose environment), you should be able to just add the following environment variable:

    environment:
      - HOST=0.0.0.0
      
However, for some reason that did not work for me so I hard-coded an IP address for this container, and then made HOST that IP address.

**Comment by robertsLando** [comment]
@Skullduggeryism try with 9.2.2

**Comment by robertsLando** [comment]
Perfect, thanks for your feedback 🙏🏼

**Pull request merged**
