### PR TITLE
chore: add arm64 pkg

### LINKED ISSUE #2730: [feat] arm64 `pkg` release?
Looking for a packaged release for arm64. 

Appears the builds here https://api.github.com/repos/zwave-js/zwave-js-ui/releases/latest are only x86_64?

### PR DESCRIPTION
**Pull request by robertsLando**
Fixes #2730

### CODE REVIEW

**Comment by robertsLando** [comment]
@kpine I'm not 100% sure this will work... on my local machine pkg uses linux static binaries for arm64 and that doesn't support node native addons, I always did such things using a custom docker container to build the executable

**Comment by robertsLando** [comment]
> Can you make a test build from a GitHub build?

What do you mean? Trigger this action to build the binaries ?

**Comment by kpine** [comment]
Sure, but I'm not sure how you get the resulting artifact. since yours is a full release. I tested with [upload-artificat](https://github.com/kpine/zwave-js-ui/blob/e95f9e8ade9bfadf5bba66cb3d7861a0ccb04829/.github/workflows/release-it.yml#L38-L54), but those aren't externally available.

Pkg wasn't using static libs for me, unless building with `linuxstatic` platform. 🤷🏻‍♂️

**Comment by juanjoSanz** [comment]
Just in case it helps, I managed to build arm64 package in a bitbucket pipeline (with amd64 docker), below the code.

If I have time, I would like to try it in github.

```
image: node:16

pipelines:
  default:
  
     - step:
        name: Build and create packages for arm64
        script:
          - id
          - dpkg --add-architecture arm64
          - apt update
          - apt install -y qemu binfmt-support qemu-user-static
          - apt install -y gcc-arm-linux-gnueabihf g++-arm-linux-gnueabihf
          - apt install -y gcc-aarch64-linux-gnu g++-aarch64-linux-gnu binutils-aarch64-linux-gnu libstdc++6-arm64-cross
          - apt install -y build-essential autoconf libtool cmake pkg-config git python-dev swig3.0 libpcre3-dev zip
          - npm install --location=global
          - npm install --location=global pkg
          - npm install --location=global pkg-fetch
          - yarn install
          - node -v
          - yarn -v
          - npm -v
          - yarn build
          - chmod +x ./package*.sh
          - ./package-arm64.sh
```

**Comment by robertsLando** [comment]
@juanjoSanz thanks for sharing your test, I will give it a try as soon as possible!

**Comment by robertsLando** [comment]
FYI I'm testing a different approach using a self hosted arm64 runner

**Comment by robertsLando** [comment]
Done, check https://github.com/zwave-js/zwave-js-ui/releases/tag/v8.6.1

**Pull request closed without merging**
